#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@service_bookmarks[-1]
	add ucitrack service_bookmarks
	set ucitrack.@service_bookmarks[-1].init=service_bookmarks
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
