#!/bin/sh /etc/rc.common
# Copyright (C) 2016 fw867 <ffkykzs@gmail.com>
# Copyright (C) 2024 Lienol

START=99

CONFIG=bookmarks
ipt="iptables -w"
ip6t="ip6tables -w"

start(){
	stop
	ENABLED=$(uci -q get ${CONFIG}.@basic[0].enable || echo "0")
	[ "${ENABLED}" != "1" ] && exit 0
	ALGOS=$(uci -q get ${CONFIG}.@basic[0].algos || echo "0")
	BOOKMARKS_ALGOS="bm"
	[ "${ALGOS}" = "1" ] && BOOKMARKS_ALGOS="kmp"

	# resolve interface
	local interface=$(
		. /lib/functions/network.sh

		network_is_up "lan" && network_get_device device "lan"
		echo "${device:-br-lan}"
	)

	$ipt -t filter -N BOOKMARKS_REJECT
	$ipt -t filter -I BOOKMARKS_REJECT -j DROP
	$ipt -t filter -I BOOKMARKS_REJECT -p tcp -j REJECT --reject-with tcp-reset
	$ipt -t filter -N BOOKMARKS_RULES
	$ipt -t filter -N BOOKMARKS
	$ipt -t filter -I BOOKMARKS -i $interface -m length --length 53:768 -j BOOKMARKS_RULES
	# $ipt -t filter -I BOOKMARKS -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	$ipt -t filter -I FORWARD -j BOOKMARKS
	
	$ip6t -t filter -N BOOKMARKS_REJECT 2>/dev/null
	$ip6t -t filter -I BOOKMARKS_REJECT -j DROP 2>/dev/null
	$ip6t -t filter -I BOOKMARKS_REJECT -p tcp -j REJECT --reject-with tcp-reset 2>/dev/null
	$ip6t -t filter -N BOOKMARKS_RULES 2>/dev/null
	$ip6t -t filter -N BOOKMARKS 2>/dev/null
	$ip6t -t filter -I BOOKMARKS -i $interface -m length --length 53:768 -j BOOKMARKS_RULES 2>/dev/null
	# $ip6t -t filter -I BOOKMARKS -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null
	$ip6t -t filter -I FORWARD -j BOOKMARKS 2>/dev/null

	local items=$(uci show ${CONFIG} | grep "=macbind" | cut -d '.' -sf 2 | cut -d '=' -sf 1)
	for i in $items; do
		enable=$(uci -q get ${CONFIG}.${i}.enable || echo "0")
		macaddr=$(uci -q get ${CONFIG}.${i}.macaddr)
		timeon=$(uci -q get ${CONFIG}.${i}.timeon)
		timeoff=$(uci -q get ${CONFIG}.${i}.timeoff)
		keyword=$(uci -q get ${CONFIG}.${i}.keyword)
		if [ "$enable" == "0" ] || [ -z "$keyword" ]; then
			continue
		fi
		if [ -z "$timeon" ] || [ -z "$timeoff" ]; then
			settime=""
		else
			settime="-m time --kerneltz --timestart $timeon --timestop $timeoff"
		fi

		if [ -z "$macaddr" ]; then
			$ipt -t filter -I BOOKMARKS_RULES $settime -m string --string "$keyword" --algo $BOOKMARKS_ALGOS -j BOOKMARKS_REJECT
			$ip6t -t filter -I BOOKMARKS_RULES $settime -m string --string "$keyword" --algo $BOOKMARKS_ALGOS -j BOOKMARKS_REJECT 2>/dev/null
		else
			$ipt -t filter -I BOOKMARKS_RULES $settime -m mac --mac-source $macaddr -m string --string "$keyword" --algo $BOOKMARKS_ALGOS -j BOOKMARKS_REJECT
			$ip6t -t filter -I BOOKMARKS_RULES $settime -m mac --mac-source $macaddr -m string --string "$keyword" --algo $BOOKMARKS_ALGOS -j BOOKMARKS_REJECT 2>/dev/null
		fi
		unset enable macaddr timeon timeoff keyword
	done

	logger -t bookmarks "bookmarks filter on $interface"
}

stop(){
	$ipt -t filter -D FORWARD -j BOOKMARKS 2>/dev/null
	$ipt -t filter -F BOOKMARKS 2>/dev/null
	$ipt -t filter -X BOOKMARKS 2>/dev/null
	$ipt -t filter -F BOOKMARKS_RULES 2>/dev/null
	$ipt -t filter -X BOOKMARKS_RULES 2>/dev/null
	$ipt -t filter -F BOOKMARKS_REJECT 2>/dev/null
	$ipt -t filter -X BOOKMARKS_REJECT 2>/dev/null
	
	$ip6t -t filter -D FORWARD -j BOOKMARKS 2>/dev/null
	$ip6t -t filter -F BOOKMARKS 2>/dev/null
	$ip6t -t filter -X BOOKMARKS 2>/dev/null
	$ip6t -t filter -F BOOKMARKS_RULES 2>/dev/null
	$ip6t -t filter -X BOOKMARKS_RULES 2>/dev/null
	$ip6t -t filter -F BOOKMARKS_REJECT 2>/dev/null
	$ip6t -t filter -X BOOKMARKS_REJECT 2>/dev/null
}
